import type { SchemaV2 } from './schemaV2';

export const defaultSchemaV2 = (): SchemaV2 => ({
  version: 3,
  MODULES: {
    INPUT: true,
    STATE_MAP: true,
    HALLUCINATION: true,
    HYPNA_MATRIX: true,
    PROMPT_GENOME: true,
    VISUAL_GRAMMAR: true,
    INFLUENCE_ENGINE: true,
    PALETTE: true,
    CONSTRAINTS: true,
    ANIMATION: false,
  },
  IGNORE_RULES: {
    hard_disable: true,
    preserve_state: true,
  },
  INPUT: {
    subject: 'Monumental surreal portrait',
    medium: 'analog photo',
    notes: 'stillness, concrete, breath',
  },
  STATE_MAP: {
    primary_state: 'ritual calm',
    secondary_state: 'anticipation',
    intensity: 70,
  },
  HALLUCINATION: {
    profile: 'light geometry drift',
    drift: 45,
  },
  HYPNA_MATRIX: {
    axis_x: 'memory',
    axis_y: 'symbol',
    depth: 65,
  },
  PROMPT_GENOME: {
    prefix: 'HYPNAGNOSIS ORACLE V3',
    structure: 'single subject, 3-part spatial read, one focal rupture',
    perception: 'parallax drift, peripheral noise, tactile depth cues',
    style_tokens: ['brutalist', 'high-contrast', 'film-grain'],
    suffix: 'avoid cheerful palette',
    seed: 42,
  },
  VISUAL_GRAMMAR: {
    framing: 'portrait',
    lens: 'normal',
    detail: 75,
  },
  INFLUENCE_ENGINE: {
    weights: {
      inkSpray: 55,
      meatBrush: 38,
      collageBreak: 52,
      networkMap: 60,
      occultDiagram: 44,
      graphicNovel: 50,
      printMaterial: 66,
      handDrawn: 58,
    },
    behavior: {
      density: 70,
      turbulence: 48,
    },
  },
  PALETTE: {
    mode: 'DESCRIPTIVE',
    lock_palette: false,
    riso_plates: [
      { hex: '#1f1f1f', role: 'keyline', opacity: 100, misregistration: 2 },
      { hex: '#f3f3ef', role: 'highlight', opacity: 82, misregistration: 1 },
    ],
    descriptive: 'graphite, bone white, silver',
    descriptive_keywords: ['graphite', 'bone', 'silver'],
    image_extract: {
      enabled: false,
      max_colors: 4,
      method: 'kmeans',
      extracted: [],
    },
    color_wheel: {
      base_hex: '#6a5cff',
      scheme: 'triadic',
      count: 4,
      rotate_deg: 0,
      generated: [],
    },
  },
  CONSTRAINTS: {
    max_tokens: 220,
    avoid: 'oversaturated colors, cartoon style',
    safety_level: 80,
  },
  ANIMATION: {
    preset: 'pulse',
    speed: 40,
    frame_count: 12,
    fps: 12,
    duration: 2,
    export_mode: 'all_frames',
    every_n: 2,
    keyframes: [
      { t: 0, curves: { 'HALLUCINATION.drift': 20, 'PALETTE.color_wheel.rotate_deg': 0 }, state: 'cold-open' },
      { t: 1, curves: { 'HALLUCINATION.drift': 70, 'PALETTE.color_wheel.rotate_deg': 180 }, state: 'crescendo' },
    ],
  },
  PROMPT_MANAGER: {
    enabled: true,
    active_prompt_id: 'prompt-001',
    compile_mode: 'BALANCED',
    style_packs: [
      { id: 'sp-newriso', name: 'Newriso', tags: ['riso', 'limited-palette', 'misregistration'], snippet: 'Style tokens: Newriso; limited palette, flat ink fields, visible overprint overlaps, slight misregistration, no gradients.', created_at: Date.now() },
      { id: 'sp-blkout', name: 'blkout-style', tags: ['erasure', 'blackout', 'found-text'], snippet: 'Found page substrate, heavy blackout/redaction, gestural marks, selective word isolation, high-contrast monochrome with occasional limited color fields.', created_at: Date.now() },
    ],
    templates: [
      {
        id: 'tpl-portrait-diagram',
        name: 'Portrait Occult Diagram',
        description: 'Portrait frame, diagrammatic, asymmetrical, riso plates.',
        tags: ['portrait', 'diagram', 'riso'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core', kind: 'CORE', enabled: true, content: 'Perception physics: astral projection weird totem of unreal figures; parallax drift, peripheral noise, tactile depth cues; matrix(memory/symbol) depth=65.' },
          { id: 'b-process', kind: 'PROCESS', enabled: true, content: 'Actions: trace hesitant hand-drawn contours and corrections; graft torn collage seams and fracture edges; overprint riso/gelli/screen textures with plate drift.' },
          { id: 'b-output', kind: 'OUTPUT_SPEC', enabled: true, content: 'Diagram: portrait frame, normal lens; clean white ground; colors only in the lines; more diagrammatic, less symmetrical.' },
          { id: 'b-neg', kind: 'NEGATIVES', enabled: true, content: 'Constraints: limited palette, flat ink fields, visible overprint overlaps, slight misregistration, no gradients; avoid cheerful palette.' },
        ],
      },

      {
        id: 'tpl-bacon',
        name: 'Bacon Pressure Field',
        description: 'Francis Bacon: fleshy distortion, containment frames, pressure, violence of space.',
        tags: ['bacon', 'distortion', 'flesh', 'pressure'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-bacon', kind: 'CORE', enabled: true, content: 'Subject / intent: figure under systemic pressure; body folding into itself; contained in a boxed field; anxiety as architecture.' },
          { id: 'b-style-bacon', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Francis Bacon; smeared flesh marks, screaming void, cage-lines; brutalist negative space; high contrast.' },
          { id: 'b-process-bacon', kind: 'PROCESS', enabled: true, content: 'Process: drag/smear/erase; repaint through; leave bruised edges; keep it human-made (visible corrections, hesitation).' },
          { id: 'b-out-bacon', kind: 'OUTPUT_SPEC', enabled: true, content: 'Output: portrait field; boxed containment geometry; figure off-center; no polish.' },
        ],
      },
      {
        id: 'tpl-basquiat',
        name: 'Basquiat Glyphstorm',
        description: 'Basquiat: raw symbolic mark-making, crowns/glyphs, scrawl, layered text, pressure of line.',
        tags: ['basquiat', 'glyphs', 'scrawl', 'text'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-basq', kind: 'CORE', enabled: true, content: 'Subject / intent: symbolic portrait or diagram-field; annotations as diagnosis; nervous energy in the margins.' },
          { id: 'b-style-basq', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Jean-Michel Basquiat; raw scrawl, crowns/glyphs, crossed-out words, diagram fragments; aggressive linework; imperfect hand.' },
          { id: 'b-process-basq', kind: 'PROCESS', enabled: true, content: 'Process: write over the image; strike-throughs; arrows; boxed phrases; let text behave like paint; keep materials visible.' },
          { id: 'b-neg-basq', kind: 'NEGATIVES', enabled: true, content: 'Avoid: clean corporate typography; avoid sterile vector polish; keep it human, noisy, urgent.' },
        ],
      },
      {
        id: 'tpl-brus',
        name: 'Brus Body-Score',
        description: 'Günter Brus: gestural body scoring, abrasion, violent line, performative mark, wound-like strata.',
        tags: ['brus', 'gesture', 'abrasion', 'body'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-brus', kind: 'CORE', enabled: true, content: 'Subject / intent: body as scored surface; collapse posture; pressure marks; the diagram is a wound map.' },
          { id: 'b-style-brus', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Günter Brus; harsh gestural marks, abrasion/scratch, bodily smears, violence of line; anti-pretty.' },
          { id: 'b-process-brus', kind: 'PROCESS', enabled: true, content: 'Process: scratch, smear, overdraw; leave damage visible; emphasize contact and friction; human error is a feature.' },
          { id: 'b-neg-brus', kind: 'NEGATIVES', enabled: true, content: 'Avoid: smooth gradients, cute motifs, glossy finish.' },
        ],
      },
      {
        id: 'tpl-lombardi',
        name: 'Lombardi Poetic Network',
        description: 'Mark Lombardi: dense analytic arcs, routing lines, labeled nodes, documentary tone—turned poetic.',
        tags: ['lombardi', 'diagram', 'network', 'analytic'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-lomb', kind: 'CORE', enabled: true, content: 'Subject / intent: event-map, routing lines, correspondence arcs; diagram as investigative poetry.' },
          { id: 'b-style-lomb', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Mark Lombardi; precise arcs and node logic; documentary density; small labels; ledger-like clarity (but allow corruption / drift).' },
          { id: 'b-process-lomb', kind: 'PROCESS', enabled: true, content: 'Process: build a network of causes/echoes; annotate with specific fragments; keep linework hand-drawn and imperfect.' },
          { id: 'b-out-lomb', kind: 'OUTPUT_SPEC', enabled: true, content: 'Output: diagram-first composition; whitespace as archive; text fragments as evidence.' },
        ],
      },
      {
        id: 'tpl-mai68',
        name: 'Mai 68 Riso Protest Sheet',
        description: 'Mai 68 poster energy: agitprop, stencil text, bold flats, urgent slogans, street print texture.',
        tags: ['mai68', 'poster', 'agitprop', 'riso'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-68', kind: 'CORE', enabled: true, content: 'Subject / intent: poster-sheet urgency; civic obstruction; public address; the prompt reads like a wall poster.' },
          { id: 'b-style-68', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Mai 68 posters; stencil fonts, blocky silhouettes, high contrast; limited inks; photocopy grit; punchy negative space.' },
          { id: 'b-process-68', kind: 'PROCESS', enabled: true, content: 'Process: bold shapes, cut-paper edges, ink misregistration; text as slogan; keep it rough and printable.' },
          { id: 'b-neg-68', kind: 'NEGATIVES', enabled: true, content: 'Avoid: glossy ad aesthetics; avoid soft gradients; keep it militant, direct.' },
        ],
      },
      {
        id: 'tpl-handmade',
        name: 'Hand‑Drawn Human‑Made',
        description: 'Hard rule: human-made finish, visible corrections, no sterile vectors, tactile print logic.',
        tags: ['handmade', 'human', 'imperfect', 'process'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-style-human', kind: 'STYLE_PACKS', enabled: true, content: 'HAND-DRAWN / HUMAN-MADE: visible pencil/pen jitter, corrections, redraws, hesitation, uneven pressure; no perfect vector lines.' },
          { id: 'b-process-human', kind: 'PROCESS', enabled: true, content: 'Process: keep seams, scuffs, tape ghosts, toner transfer artifacts; allow misregistration; embrace wrongness; avoid digital polish.' },
          { id: 'b-constraints-human', kind: 'CONSTRAINTS', enabled: true, content: 'Constraints: prioritize tactile marks; forbid sterile cleanliness; no gradient airbrush look.' },
        ],
      },
    ],
    prompts: [
      {
        id: 'prompt-001',
        name: 'Active Prompt',
        description: 'Block-based prompt (editable).',
        tags: ['active'],
        created_at: Date.now(),
        updated_at: Date.now(),
        blocks: [
          { id: 'p-core', kind: 'CORE', enabled: true, content: 'Subject / intent: Monumental surreal portrait; hypnagogic hallucination physics; drift=45; matrix(memory/symbol) depth=65.' },
          { id: 'p-style', kind: 'STYLE_PACKS', enabled: true, content: 'Style tokens: brutalist, high-contrast, film-grain. (Optionally apply a style pack.)' },
          { id: 'p-palette', kind: 'PALETTE_PACK', enabled: true, content: 'Palette: use extracted or locked plates if set; otherwise descriptive graphite/bone white/silver.' },
          { id: 'p-process', kind: 'PROCESS', enabled: true, content: 'Process: hesitant hand-drawn contours + corrections; torn collage seams; plate drift overprint.' },
          { id: 'p-constraints', kind: 'CONSTRAINTS', enabled: true, content: 'Constraints: limited palette, flat ink fields, visible overprint overlaps, slight misregistration, no gradients.' },
          { id: 'p-neg', kind: 'NEGATIVES', enabled: true, content: 'Avoid: cheerful palette, oversaturated colors, cartoon style.' },
        ],
      },

      {
        id: 'tpl-bacon',
        name: 'Bacon Pressure Field',
        description: 'Francis Bacon: fleshy distortion, containment frames, pressure, violence of space.',
        tags: ['bacon', 'distortion', 'flesh', 'pressure'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-bacon', kind: 'CORE', enabled: true, content: 'Subject / intent: figure under systemic pressure; body folding into itself; contained in a boxed field; anxiety as architecture.' },
          { id: 'b-style-bacon', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Francis Bacon; smeared flesh marks, screaming void, cage-lines; brutalist negative space; high contrast.' },
          { id: 'b-process-bacon', kind: 'PROCESS', enabled: true, content: 'Process: drag/smear/erase; repaint through; leave bruised edges; keep it human-made (visible corrections, hesitation).' },
          { id: 'b-out-bacon', kind: 'OUTPUT_SPEC', enabled: true, content: 'Output: portrait field; boxed containment geometry; figure off-center; no polish.' },
        ],
      },
      {
        id: 'tpl-basquiat',
        name: 'Basquiat Glyphstorm',
        description: 'Basquiat: raw symbolic mark-making, crowns/glyphs, scrawl, layered text, pressure of line.',
        tags: ['basquiat', 'glyphs', 'scrawl', 'text'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-basq', kind: 'CORE', enabled: true, content: 'Subject / intent: symbolic portrait or diagram-field; annotations as diagnosis; nervous energy in the margins.' },
          { id: 'b-style-basq', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Jean-Michel Basquiat; raw scrawl, crowns/glyphs, crossed-out words, diagram fragments; aggressive linework; imperfect hand.' },
          { id: 'b-process-basq', kind: 'PROCESS', enabled: true, content: 'Process: write over the image; strike-throughs; arrows; boxed phrases; let text behave like paint; keep materials visible.' },
          { id: 'b-neg-basq', kind: 'NEGATIVES', enabled: true, content: 'Avoid: clean corporate typography; avoid sterile vector polish; keep it human, noisy, urgent.' },
        ],
      },
      {
        id: 'tpl-brus',
        name: 'Brus Body-Score',
        description: 'Günter Brus: gestural body scoring, abrasion, violent line, performative mark, wound-like strata.',
        tags: ['brus', 'gesture', 'abrasion', 'body'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-brus', kind: 'CORE', enabled: true, content: 'Subject / intent: body as scored surface; collapse posture; pressure marks; the diagram is a wound map.' },
          { id: 'b-style-brus', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Günter Brus; harsh gestural marks, abrasion/scratch, bodily smears, violence of line; anti-pretty.' },
          { id: 'b-process-brus', kind: 'PROCESS', enabled: true, content: 'Process: scratch, smear, overdraw; leave damage visible; emphasize contact and friction; human error is a feature.' },
          { id: 'b-neg-brus', kind: 'NEGATIVES', enabled: true, content: 'Avoid: smooth gradients, cute motifs, glossy finish.' },
        ],
      },
      {
        id: 'tpl-lombardi',
        name: 'Lombardi Poetic Network',
        description: 'Mark Lombardi: dense analytic arcs, routing lines, labeled nodes, documentary tone—turned poetic.',
        tags: ['lombardi', 'diagram', 'network', 'analytic'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-lomb', kind: 'CORE', enabled: true, content: 'Subject / intent: event-map, routing lines, correspondence arcs; diagram as investigative poetry.' },
          { id: 'b-style-lomb', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Mark Lombardi; precise arcs and node logic; documentary density; small labels; ledger-like clarity (but allow corruption / drift).' },
          { id: 'b-process-lomb', kind: 'PROCESS', enabled: true, content: 'Process: build a network of causes/echoes; annotate with specific fragments; keep linework hand-drawn and imperfect.' },
          { id: 'b-out-lomb', kind: 'OUTPUT_SPEC', enabled: true, content: 'Output: diagram-first composition; whitespace as archive; text fragments as evidence.' },
        ],
      },
      {
        id: 'tpl-mai68',
        name: 'Mai 68 Riso Protest Sheet',
        description: 'Mai 68 poster energy: agitprop, stencil text, bold flats, urgent slogans, street print texture.',
        tags: ['mai68', 'poster', 'agitprop', 'riso'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-core-68', kind: 'CORE', enabled: true, content: 'Subject / intent: poster-sheet urgency; civic obstruction; public address; the prompt reads like a wall poster.' },
          { id: 'b-style-68', kind: 'STYLE_PACKS', enabled: true, content: 'Influence: Mai 68 posters; stencil fonts, blocky silhouettes, high contrast; limited inks; photocopy grit; punchy negative space.' },
          { id: 'b-process-68', kind: 'PROCESS', enabled: true, content: 'Process: bold shapes, cut-paper edges, ink misregistration; text as slogan; keep it rough and printable.' },
          { id: 'b-neg-68', kind: 'NEGATIVES', enabled: true, content: 'Avoid: glossy ad aesthetics; avoid soft gradients; keep it militant, direct.' },
        ],
      },
      {
        id: 'tpl-handmade',
        name: 'Hand‑Drawn Human‑Made',
        description: 'Hard rule: human-made finish, visible corrections, no sterile vectors, tactile print logic.',
        tags: ['handmade', 'human', 'imperfect', 'process'],
        created_at: Date.now(),
        blocks: [
          { id: 'b-style-human', kind: 'STYLE_PACKS', enabled: true, content: 'HAND-DRAWN / HUMAN-MADE: visible pencil/pen jitter, corrections, redraws, hesitation, uneven pressure; no perfect vector lines.' },
          { id: 'b-process-human', kind: 'PROCESS', enabled: true, content: 'Process: keep seams, scuffs, tape ghosts, toner transfer artifacts; allow misregistration; embrace wrongness; avoid digital polish.' },
          { id: 'b-constraints-human', kind: 'CONSTRAINTS', enabled: true, content: 'Constraints: prioritize tactile marks; forbid sterile cleanliness; no gradient airbrush look.' },
        ],
      },
    ],
    history: [],
  },
});
